package Frame;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alexis
 */
public class JFrameParametres extends javax.swing.JFrame {

    /**
     * Creates new form JFrameParametres
     */
    public JFrameParametres() throws IOException {
        initComponents();
        setLocationRelativeTo(null);
        this.chargerDonneesFichier();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_IpBdd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField_PortBdd = new javax.swing.JTextField();
        jButton_sauvegarder = new javax.swing.JButton();
        jButton_annuler = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCheckBoxNotification = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldUtilisateur = new javax.swing.JTextField();
        jTextFieldMotDePasse = new javax.swing.JTextField();
        jTextFieldNomBDD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setTitle("Paramètres");

        jLabelTitre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTitre.setText("Paramètres");

        jLabel2.setText("BDD serveur");

        jLabel1.setText("BDD port");

        jButton_sauvegarder.setText("Sauvegarder");
        jButton_sauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sauvegarderActionPerformed(evt);
            }
        });

        jButton_annuler.setText("Annuler");
        jButton_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_annulerActionPerformed(evt);
            }
        });

        jLabel3.setText("Notification");

        jLabel4.setText("Utilisateur");

        jLabel5.setText("Mot de passe");

        jLabel6.setText("Nom BDD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitre)
                .addGap(160, 160, 160))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxNotification))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNomBDD)
                                    .addComponent(jTextField_IpBdd)
                                    .addComponent(jTextField_PortBdd, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(jTextFieldUtilisateur)
                                    .addComponent(jTextFieldMotDePasse)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jButton_sauvegarder)
                        .addGap(52, 52, 52)
                        .addComponent(jButton_annuler)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_IpBdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_PortBdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomBDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3))
                    .addComponent(jCheckBoxNotification))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_sauvegarder)
                    .addComponent(jButton_annuler))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_annulerActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton_annulerActionPerformed

    private void jButton_sauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sauvegarderActionPerformed
        try {
            this.sauvegarderDonneesFichier();
        } catch (IOException ex) {
            Logger.getLogger(JFrameParametres.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_sauvegarderActionPerformed

    /*
    Charge les données des fichiers parametresBdd.properties et parametres.
    */
    public void chargerDonneesFichier() throws FileNotFoundException, IOException {
        try (InputStream input = new FileInputStream("parametresBdd.properties")) {
            Properties prop = new Properties();

            prop.load(input);

            this.jTextField_IpBdd.setText(prop.getProperty("ip"));
            this.jTextField_PortBdd.setText(prop.getProperty("port"));
            this.jTextFieldUtilisateur.setText(prop.getProperty("utilisateur"));
            this.jTextFieldMotDePasse.setText(prop.getProperty("motDePasse"));
            this.jTextFieldNomBDD.setText(prop.getProperty("nomBase"));

        } catch (IOException ex) {
            ex.printStackTrace();
        }
        try (InputStream input = new FileInputStream("parametres.properties")) {
            Properties prop = new Properties();

            prop.load(input);

            this.jCheckBoxNotification.setSelected(Boolean.parseBoolean(prop.getProperty("notification")));

        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    /*
    Sauvegarde les données des jTextField dans les fichiers properties.
    */
    public void sauvegarderDonneesFichier() throws FileNotFoundException, IOException {
        String mail = "";
        String mdp = "";
        try (OutputStream output = new FileOutputStream("parametresBdd.properties")) {

            Properties prop = new Properties();

            prop.setProperty("ip", this.jTextField_IpBdd.getText());
            prop.setProperty("motDePasse", this.jTextFieldMotDePasse.getText());
            prop.setProperty("nomBase", this.jTextFieldNomBDD.getText());
            prop.setProperty("utilisateur", this.jTextFieldUtilisateur.getText());
            prop.setProperty("port", this.jTextField_PortBdd.getText());
            prop.setProperty("driver", "com.mysql.jdbc.Driver");
            prop.setProperty("protocole", "jdbc:mysql:");

            prop.store(output, null);
        } catch (IOException io) {
            io.printStackTrace();
        }
        try (InputStream input = new FileInputStream("parametres.properties")) {
            Properties prop = new Properties();

            prop.load(input);

            mail = prop.getProperty("mail");
            mdp = prop.getProperty("mdp_mail");
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        try (OutputStream output = new FileOutputStream("parametres.properties")) {
            Properties prop = new Properties();
            prop.setProperty("notification", Boolean.toString(this.jCheckBoxNotification.isSelected()));
            prop.setProperty("mail", mail);
            prop.setProperty("mdp_mail", mdp);
            System.out.println();
            prop.store(output, null);
        } catch (IOException io) {
            io.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameParametres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameParametres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameParametres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameParametres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFrameParametres().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(JFrameParametres.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_annuler;
    private javax.swing.JButton jButton_sauvegarder;
    private javax.swing.JCheckBox jCheckBoxNotification;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JTextField jTextFieldMotDePasse;
    private javax.swing.JTextField jTextFieldNomBDD;
    private javax.swing.JTextField jTextFieldUtilisateur;
    private javax.swing.JTextField jTextField_IpBdd;
    private javax.swing.JTextField jTextField_PortBdd;
    // End of variables declaration//GEN-END:variables
}
